import { useState } from "react";
import { RefreshCw } from "lucide-react";
import { useApi } from "@/hooks/useApi";
import { ordersApi } from "@/lib/api";
import { formatCurrency, formatDate, cn } from "@/lib/utils";
import type { Order, OrderStatus } from "@/lib/types";
import { ORDER_STATUS_LABEL, ORDER_STATUS_COLOR } from "@/lib/types";
const STATUSES:OrderStatus[]=["pending","payment_confirmed","preparing","ready","delivering","delivered","cancelled"];
export default function Pedidos(){const[filter,setFilter]=useState<OrderStatus|undefined>();const{data:orders,loading,reload}=useApi<Order[]>(()=>ordersApi.list(filter,100),[filter]);const[upd,setUpd]=useState<string|null>(null);async function change(id:string,status:OrderStatus){setUpd(id);try{await ordersApi.updateStatus(id,status);reload();}catch{}finally{setUpd(null);}}return(<div className="space-y-6"><div className="flex items-center justify-between"><div><h1 className="text-xl font-bold text-gray-900">Pedidos</h1><p className="text-sm text-gray-500">{orders?.length??0} pedido(s)</p></div><div className="flex gap-2"><select value={filter??""} onChange={e=>setFilter((e.target.value as OrderStatus)||undefined)} className="h-9 rounded-lg border border-gray-200 bg-white px-3 text-sm focus:outline-none focus:ring-2 focus:ring-blue-500"><option value="">Todos</option>{STATUSES.map(s=><option key={s} value={s}>{ORDER_STATUS_LABEL[s]}</option>)}</select><button onClick={reload} disabled={loading} className="h-9 w-9 rounded-lg border border-gray-200 bg-white flex items-center justify-center hover:bg-gray-50"><RefreshCw className={`h-4 w-4 ${loading?"animate-spin":""}`}/></button></div></div><div className="space-y-2">{orders?.map(o=>(<div key={o.id} className="rounded-lg border border-gray-100 bg-white shadow-[4px_4px_4px_0px_rgba(27,118,242,0.08)] p-4"><div className="flex items-start justify-between gap-4"><div className="space-y-1 flex-1"><div className="flex items-center gap-2 flex-wrap"><span className="text-xs font-mono text-gray-400">#{o.id.slice(-6)}</span><span className={cn("inline-flex items-center rounded-full px-2.5 py-0.5 text-xs font-medium",ORDER_STATUS_COLOR[o.status])}>{ORDER_STATUS_LABEL[o.status]}</span>{o.pix_confirmed&&<span className="rounded-full bg-green-50 px-2 py-0.5 text-xs text-green-700 font-medium">PIX ✓</span>}</div><p className="text-sm text-gray-600">{o.items.map(i=>`${i.quantity}x ${i.product_name}`).join(", ")}</p><p className="text-xs text-gray-400">{formatDate(o.created_at)}{o.delivery_building_block&&` · Bloco ${o.delivery_building_block}${o.delivery_apartment?` Ap ${o.delivery_apartment}`:""}`}</p></div><div className="flex flex-col items-end gap-2"><span className="font-bold text-gray-900">{formatCurrency(o.total_amount)}</span><select value={o.status} onChange={e=>change(o.id,e.target.value as OrderStatus)} disabled={upd===o.id} className="h-8 rounded-lg border border-gray-200 bg-white px-2 text-xs focus:outline-none focus:ring-2 focus:ring-blue-500">{STATUSES.map(s=><option key={s} value={s}>{ORDER_STATUS_LABEL[s]}</option>)}</select></div></div></div>))}{!loading&&orders?.length===0&&<div className="rounded-lg border border-gray-100 bg-white p-12 text-center text-gray-400">Nenhum pedido.</div>}</div></div>);}
